### ISSUE TITLE
Implement book scraping

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/mymickiewicz-data-scraper#3]
## Description

Download all the books from [here](https://wolnelektury.pl/katalog/autor/adam-mickiewicz/) in `txt` format.

## TODO

- [x] Get each book's titles: `$x('//*[@id="book-list"]/article/h2/a')`
- [x] Use the titles to get download URLs: `https://wolnelektury.pl/media/book/txt/<title>.txt`
- [ ] Get the texts (if `404` try downloading in another format)

EPUB -> TXT is the best option (if txt is not available) because it's just XML and just convert it with:

- [pandoc](https://pandoc.org/)
- [node-pandoc](https://www.npmjs.com/package/node-pandoc)

## Resources

- [Cleaning up pdftotext font issues](https://superuser.com/questions/220363/cleaning-up-pdftotext-font-issues)

- [PDF to TEXT](https://www.npmjs.com/package/pdf-to-text)
- [EPUB to TEXT](https://github.com/Projet-TAMIS/epub-to-text)
- [ebook-convert](https://github.com/sethvincent/ebook-convert)
