### ISSUE TITLE
Implementing prep steps

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/mymickiewicz-data-scraper#6]
## Description

Implement steps to mkae data usable in training.

## TODO

- [ ] Remove info from top of file
- [ ] Remove info from bottom of file
- [ ] Remove all text that's not in Polish
- [ ] Check for other things

## Resources

- [ ] [regex101](https://regex101.com/)
- [ ] [`languagedetect`](https://www.npmjs.com/package/languagedetect)
